// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package types

import (
	"time"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// FileEntry defines model for FileEntry.
type FileEntry struct {
	IsDir      bool      `json:"is_dir"`
	ModifiedAt time.Time `json:"modified_at"`
	Name       string    `json:"name"`
	Path       string    `json:"path"`
	Size       int64     `json:"size"`
}

// FileListResponse defines model for FileListResponse.
type FileListResponse struct {
	Entries []FileEntry `json:"entries"`
	Path    string      `json:"path"`
}

// ListFilesParams defines parameters for ListFiles.
type ListFilesParams struct {
	// Path Relative path from configured root, usually starting with /
	Path string `form:"path" json:"path"`
}

// GetFileContentParams defines parameters for GetFileContent.
type GetFileContentParams struct {
	// Path Relative path from configured root
	Path string `form:"path" json:"path"`
}
